services:
  streamlit-app:
    build: .
    image: hodgejs/PyTrading:v1.0
    container_name: PyTrading-Streamlit
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: always